server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwerty
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: author-service
          uri: lb://author-service
          predicates:
            - Path=/author/**
          filters:
            - RewritePath=/author/(?<path>.*), /$\{path}
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book/**
          filters:
            - RewritePath=/book/(?<path>.*), /$\{path}
        - id: account-service
            uri: lb://account-service
            predicates:
              - Path=/account/**
            filters:
              - RewritePath=/account/(?<path>.*), /$\{path}

jwt:
  provider:
    security: soymun
    validate: 3600000

management:
  endpoints:
    web:
      exposure:
        include: "*"